import os
import time
from typing import Dict, Tuple
from .base_manager import BaseManager


class NTPManager(BaseManager):
    """NTP 管理類別"""
    
    CHRONY_CONFIG_TEMPLATE = """# Chrony NTP Server Configuration
# Generated by Bastion Install Wizard
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
hwtimestamp *
allow
local stratum 8
bindcmdaddress 0.0.0.0
"""
    
    def generate_config(self) -> str:
        """生成 NTP 配置內容"""
        # 如果有上游 NTP 伺服器，添加到配置中
        config = self.CHRONY_CONFIG_TEMPLATE
        
        ntp_upstream = self.config.get('ntp_upstream', '')
        if ntp_upstream:
            config = config.replace(
                "# Use public servers",
                f"server {ntp_upstream} iburst\n# Use public servers"
            )
        
        return config
    
    def install(self) -> Tuple[bool, str]:
        """安裝並設定 NTP 伺服器"""
        self._log("開始設定 NTP 伺服器 (chrony)...")
        
        # 安裝 chrony
        success, _, err = self._run_command("yum install -y chrony")
        if not success:
            return False, f"chrony 安裝失敗: {err}"
        
        # 備份原始配置
        chrony_conf = '/etc/chrony.conf'
        self._backup_file(chrony_conf)
        
        # 寫入 NTP 配置
        chrony_config = self.generate_config()
        if not self._write_file(chrony_conf, chrony_config):
            return False, "寫入 NTP 配置檔失敗"
        
        # 重啟 chronyd
        success, _, err = self._run_command("systemctl restart chronyd")
        if not success:
            return False, f"chronyd 啟動失敗: {err}"
        
        self._run_command("systemctl enable chronyd")
        
        # 檢查時間同步狀態
        time.sleep(2)  # 等待服務穩定
        
        if self._check_service_status("chronyd"):
            # 檢查同步狀態
            success, stdout, _ = self._run_command("chronyc tracking | grep -E 'Leap status|Stratum'")
            return True, f"NTP 伺服器已成功配置並啟動\n{stdout}"
        else:
            return False, "NTP 伺服器啟動失敗"